### ISSUE TITLE
Existing Record condition?

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#42]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/3896852da56e3d14154ccc634ca22461b384146c/chapter11/whatstore/module/Store/src/Model/Customer.php#L63

How do you verify that a user has not already registered as a customer with the email that is being passed? I would think that duplicate accounts would be an unwanted condition.

**Comment by fgsl** [comment]
Really, e-mail could be a unique key. But I don't know if this is essential here.

For example, I have to care everything for my father when he needs to create a virtual account. When I need to fill the e-mail field, I put my address, because he never will read an e-mail message. If the register required only one e-mail address per account, this  would be only a way to create digital divide in my case.

**Comment by tyrsson** [comment]
Well, if its for your father or not, its still, in that circumstance your account. Nowhere in the code do you allow the association of two accounts. True, its for him, but its your account. Still two distinct entities.

Otherwise you would need something like a company account, which supports multiple users "per account". Maybe they are all billed to the same corporate account? Or they have multiple "representatives" per account in the system. Either way, that is outside the use case of the application for which I am reading code. In this particular use case, your use case, how and where do you address password ambiguity? Are you using his password and your email address? Most likely not, and since he will never check email anyway, he does not need an email in the system and your account should be the sole identifier.  Which, again, means it can and should be unique. 
Does the application at any time verify the email address of the user?
