### ISSUE TITLE
Ci coverage for MVC context

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#46]
I'm curious as to why the book does not cover continuous integration and static analysis within the text? Laminas provides github actions for both and would only take brief explanations to cover within the text. I also wonder why with all of the focus on PhpUnit why there is no mention of laminas-test? I can understand in the initial setup but I figured it would at least be mentioned, if not used, with the move to MVC context.

**Comment by fgsl** [comment]
From the end to beginning, laminas-test is mentioned in Chapter 4. 

There is a little about static analysis in Chapter 12, limited to replicated code, but I really didn't think about continuous integration as an essential element for this book, except as note. I don't know if Github will be used as CI/CI provider and I don't want to imprison the reader with a specific environment. 

I don't know. Many things and nothing are the same for me. I am very influenced by this quotation:

[...] “I consider that a man’s brain originally is like a little empty attic, and you have to stock it with such furniture as you choose. A fool takes in all the lumber of every sort that he comes across, so that the knowledge which might be useful to him gets crowded out, or at best is jumbled up with a lot of other things so that he has a difficulty in laying his hands upon it. Now the skilful workman is very careful indeed as to what he takes into his brain-attic. He will have nothing but the tools which may help him in doing his work, but of these he has a large assortment, and all in the most perfect order. It is a mistake to think that that little room has elastic walls and can distend to any extent.[...] DOYLE, Sir Arthur Conan. _A Study in Scarlet_.
 
I always remember this when I expect my students to do several things simultaneously. They usually do these three: listen, ignore, and forget.

**Comment by tyrsson** [comment]
True,

However, the reason I mention it is this. 99% of the time when working with frameworks, the framework maintainers usually provide a huge amount of tooling, especially in regards to Laminas, that the developer can utilize to speed up development. This is especially true when testing a Laminas/Mezzio application since it provides many of the assertions that a developer will need to test in a MVC context.  This extends beyond Laminas since many frameworks provide tools such as these. I can not think of a single reason why a developer would not want to use these tools (if they can be incorporated in their dev environment and workflow) considering the amount of time they save the developer not to mention the improvement in code consistency and quality. In the text you say (I am paraphrasing here) that a developer should choose the tools that are appropriate and most productive for the task at hand. I think this discussion directly applies to that context. If a developer can spend 2 hours reading and learning how to incorporate the tools into a project and the result is saving them 2000 hours before the project is finished. Well, the number would speak for themselves would they not? Because for those students that soon become lead developers or already are lead developers, its a huge benefit especially considering how flexible the Laminas tooling is. As an example you can add nearly any custom job. Does not even have to be php focused and since it runs at the repo level, it enforces those decisions across the entire team of those working on the project. It can use private repos, custom jobs, custom images. Its extremely flexible. The official repo's usually use psalm, I personally use phpstan for static analysis. It literally takes 9 lines of code, the addition of .laminas-ci files in the project root and adding the github action to the project. Which, is comprised of enabling github actions on the repo and copying the correct .yml file into the correct directory. Then, regardless of whether a developer has the tools setup in their dev environment and are doing the correct testing locally, the checks are still performed on the code before its committed.
Keep in mind, I would be saying the same thing if it was codeignitor, symphony, laravel. The tooling is provided for a reason, with the amount of time that is spent on tooling in the beginning of the book I really would expect to learn about this if I purchased the book especially when you show how easy it is to integrate this tooling into IDE's such as Eclipse.
