### ISSUE TITLE
Chapter 11 Customer Model

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#49]
Missing returns types for methods
exchangeArray
encrypt (method needs removed actually)
toArray

If you pass a flag that has a default, you could possibly send the password back as well, if you needed it.
toArray($filterPassword = true)

**Comment by fgsl** [comment]
* exchangeArray: added void as return type for abstract model and its childrens;
* encrypt (method needs removed actually): if it needs to be removed, why to add, right?
* toArray: the return type in exchangeArray is a useful change because documents the code. As Zend of Python says, explicit is better than explicit. But toArray is explicit and there are no complex possibilities to generate another type. i don't fell that control is strictly required here.

**Comment by tyrsson** [comment]
The recommendation was based solely for static analysis. No return type will cause an issue with nearly any tooling that is used.

**Comment by fgsl** [comment]
> The recommendation was based solely for static analysis. No return type will cause an issue with nearly any tooling that is used.

I will think about it when I am adjusting Chapter 12, because it has a little of static analysis. Maybe this could be inserted with another analysis tool.

**Comment by tyrsson** [comment]
It could actually just be a comment. Both phpstan and psalm will look for the actual return type, if none is found it will check the method doc comment block to see how it is detailed.

/** @return array<string, mixed> $data * /
 Just as a basic example
