### ISSUE TITLE
Refactor form rendering configuration according to more appropriate way

### ISSUE THREAD

**Issue by fgsl** [PacktPublishing/Laminas-Web-Development#55]
Reference: https://discourse.laminas.dev/t/documentation-about-form-component-rendering-with-laminas-mvc/3027

**Comment by tyrsson** [comment]
I finally had time to read the thread in the forum.

Here is a couple things to consider.

1. Since laminas-mvc-form is only a meta package, you can NOT just add it to the modules.config.php etc. You run a composer require for it. During that install, it installs the 3 packages that are needed for usage in the MVC if you are going to integrate it fulling into the MVC. Two of which are absolute requirements if you are going to use any of the view helpers for form rendering. 99.9% of the time that will be the case.
2. The reason why the i8ln package is required, is because laminas\form\src\view\helper\abstracthelper extends Laminas\I18n\View\Helper\AbstractTranslatorHelper Which is your coupling.
3. Its usually much simpler to just tell new laminas users to not select the "minimal" build, have them select yes when it prompts for laminas-form, and any other package that is required for the project. Result, you end up with doctrine annotations that will not be used in the text. If by some chance they are advanced composer users and select to require dev it, then they will get the package anyway as a dev requirement for laminas-form, which would make the point of not loading doctrine annotations moot anyway.

In the "suggest" block of the laminas-form package composer.json it gives the following reason for suggesting laminas/laminas-i18n. The read me of the laminas-mvc-form repo also explains this, but not as well IMO.

> "laminas/laminas-i18n": "^2.12, required when using laminas-form view helpers"

As a general rule of thumb, any package that exposes a Module.php file will need to be added to the modules array, ie /config/modules.config.php.

Which brings me to my next point, which applies to all laminas packages. If they contain a Module.php they need to be added to the modules.config.php file. I think what tripped you up (possibly) is that laminas-form was installed before the skeleton, which means that laminas-component-installer most likely was not in use. Which in turns means that it was not automatically injected into the modules.config.php array. You brought laminas-form over from the pre MVC context (possibly, its hard to recall, since I have bounced back and forth between the early chapters and not had a chance to read every page of them). Which means that its Module.php file was not called, and its ConfigProvider was not called, which means, the view helper services and aliases was never registered with the service manager. Of course they are still available via autoloading. When you ran the Eclipse tooling to update the dependencies that makes the classes available via autoloading. That, however, does not add it to the modules.config.php file and the execution of the config provider in this case is what makes them available as services via the view helper plugin manager, whether it be by alias or by service name.
You may want to take a look at Laminas/View/Renderer/PhpRenderer since they are called through its context via __call which just proxies the call to the view helper plugin manager.

You can find a very good explanation of the aforementioned information in the docs for the component installer.
