### ISSUE TITLE
Every user is a role?

### ISSUE THREAD

**Issue by tyrsson** [PacktPublishing/Laminas-Web-Development#63]
https://github.com/PacktPublishing/Laminas-Web-Development/blob/b1e6384e2d14c074fee41aeecbe41aba54e31f00/chapter12/whatstore/module/Inventory/src/Model/IdentityManager.php#L64

Am I seeing this correctly? Is every user seen as a role in the application?

**Comment by fgsl** [comment]
In fact, the authorization control is about the roles, not about the user. More accurately, is about the permissions. Here, several roles are abstracted to a single role. 

There is no need to produce several objects because there are several roles in database table. What matters are the permissions. User can have several roles and each one of them has different permissions. If some role allows user to do something, this is what matters.
